# diag_parser.R
#
# An automated graphing system to process GCAM output data (as generated by the
# ModelInterface) and generate both standard and user-defined graphs.
#
# Author: Jingyang Song, Peking University; Jul 2026;

# -----------------------------------------------------------------------------
# parse_mi_output: parse the ModelInterface output
# It tries to be smart, only reading the tables that will actually be needed
parse_mi_output <- function( fn ) {

    tables <- list()

    # See if the user has provided any values overriding our defaults
    use_tablenames <- TRUE
    headerline <- "scenario"
    yearpat <- "X[0-9]{4}"

    printlog( "Reading", fn, "...", cr=F, level=LOGLEVEL_SUMMARY )
    tryCatch( {
        fdata <- scan( fn, what=character(), sep="\n", blank.lines.skip=F, quiet=T )
    }, error=function( err ) {
        printlog( "error reading file" )
        printlog( as.character( err ) )
        stop()
    } )

    printlog( "OK.", ts=F )
    tableheaders <- grep( headerline, fdata )
    printlog( "Table headers located in lines", tableheaders )
    table_name <- NA

    for( i in 1:length( tableheaders ) ) {
        if( use_tablenames ) {
            table_name <- fdata[ tableheaders[ i ]-1 ]

            if( table_name %in% names( tables ) ) {
                printlog( "Table name", table_name, "has already been read!" )
                stop()
            }
        } else {
            table_name <- i
        }
        printlog( "Table", i, "name is", table_name )
#       if( !( table_name %in% tables_needed ) ) {
#           printlog( "Table", table_name, "not needed, skipping" )
#           next
#       }

        nskip <- tableheaders[ i ] - 1
        headers <- fdata[ tableheaders[ i ] ]
        extrafields <- 0
        while( substr( headers, nchar( headers), nchar( headers ) )=="," ) {
            headers <- substr( headers, 1, nchar( headers )-1 )
            extrafields <- extrafields + 1
        }
#       printlog( "Extra fields =", extrafields )

        if( i==length( tableheaders ) )
            nrows <- -1
        else
            nrows <- tableheaders[ i+1 ] - tableheaders[ i ] - 1 - use_tablenames       # i.e., subtract 1 if using table names

        printlog( "Reading table", i, "in", fn, "( skip =", nskip, " nrows =", nrows, ")" )
        tempdata <- read.table( fn, row.names=NULL, skip=nskip, nrows=nrows, header=T,
            stringsAsFactors=F, sep=",", comment.char=GCAM_DATA_COMMENT ) #stringsAsFactors=F,

        # Remove extra columns on end - this is often present in the MI output
        if( extrafields > 0 ) {
            printlog( "Removing", extrafields, "extra fields" )
            tempdata <- tempdata[ -seq( ncol( tempdata ) - extrafields+1, ncol( tempdata ) ) ]
        }

        printlog( "nrow =", nrow( tempdata ), "ncol =", ncol( tempdata ) )

        # Extract scenario and date
        if( SCENARIO_FIELD_NAME %in% names( tempdata ) ) {
#           printlog( "Separating scenario and date" )
            splitinfo <- str_split_fixed( tempdata[ , SCENARIO_FIELD_NAME ], ",date=", 2 )
            tempdata$scenario <- splitinfo[ , 1 ]
            tempdata$date <- splitinfo[ , 2 ]
        }

        # Extract AEZ, if available - this is very specific and breakable
        searchstring <- "AEZ[0-9]{1}"
        splitstring <- "AEZ"
        if( !is.na( splitstring ) ) {
#           printlog( "Looking for", splitstring )
            for( j in 1:ncol( tempdata ) ) {
                if( grepl( searchstring, tempdata[ 1, j ] ) ) {
                    printlog( splitstring, "data located in column", j )
                    dtemp <- as.data.frame( str_split_fixed( tempdata[ , j ], splitstring, 2 ) )
#                   print(head(dtemp))
                    tempdata[ , j ] <- dtemp[ , 1 ]
                    tempdata[ splitstring ] <- dtemp[,2] #as.factor( as.numeric( dtemp[ , 2 ] ) )
                }
            }
        }

#       printlog( "Melting..." )
        yearfields <- grep( yearpat, names( tempdata ) )
        tempdata <- melt( tempdata, measure.vars=yearfields )

        # Make a better year field and assign file name field
        tempdata$Year <- as.numeric( substr( tempdata$variable, 2, length( tempdata$variable ) ) )
        tempdata$variable <- NULL
        tempdata[ , FILE_FIELD_NAME ] <- strsplit( basename( fn ), ".csv" )[[ 1 ]][ 1 ]

        tables[[ table_name ]] <- tempdata
    } # for i

    return( tables )
} # parse_mi_output

parse_mi_output_pic <- function( fn ) {

    tables <- list()

    # See if the user has provided any values overriding our defaults
    use_tablenames <- TRUE
    headerline <- "scenario"
    yearpat <- "X[0-9]{4}"

    printlog( "Reading", fn, "...", cr=F, level=LOGLEVEL_SUMMARY )
    tryCatch( {
        fdata <- scan( fn, what=character(), sep="\n", blank.lines.skip=F, quiet=T )
        error_lines <- grep("had error: java\\.lang\\.Exception: The query returned no results\\.", scan(fn, what=character(), sep="\n", quiet=TRUE))
    }, error=function( err ) {
        printlog( "error reading file" )
        printlog( as.character( err ) )
        stop()
    } )

    printlog( "OK.", ts=F )
    tableheaders <- grep( headerline, fdata )
    printlog( "Table headers located in lines", tableheaders )
    table_name <- NA

    for( i in 1:length( tableheaders ) ) {
        if( use_tablenames ) {
            table_name <- fdata[ tableheaders[ i ]-1 ]
        } else {
            table_name <- i
        }
        printlog( "Table", i, "name is", table_name )

        nskip <- tableheaders[ i ] - 1
        headers <- fdata[ tableheaders[ i ] ]
        extrafields <- 0
        while( substr( headers, nchar( headers), nchar( headers ) )=="," ) {
            headers <- substr( headers, 1, nchar( headers )-1 )
            extrafields <- extrafields + 1
        }

        if( i==length( tableheaders ) ){
            nrows <- length(fdata) - tableheaders[ i ]
            error_inside <- error_lines[error_lines >= tableheaders[i]]
        }else{
            nrows <- tableheaders[ i+1 ] - tableheaders[ i ] - 1 - use_tablenames       # i.e., subtract 1 if using table names
            error_inside <- error_lines[error_lines >= tableheaders[ i ] & error_lines <= tableheaders[ i +1]]
        }
        nrows_corrected <- nrows - length(error_inside)

        printlog( "Reading table", i, "in", fn, "( skip =", nskip, " nrows =", nrows_corrected, ")" )
        tempdata <- read.table( fn, row.names=NULL, skip=nskip, nrows=nrows_corrected, header=T,
                                stringsAsFactors=F, sep=",", comment.char=GCAM_DATA_COMMENT ) #stringsAsFactors=F,

        # Remove extra columns on end - this is often present in the MI output
        if( extrafields > 0 ) {
            printlog( "Removing", extrafields, "extra fields" )
            tempdata <- tempdata[ -seq( ncol( tempdata ) - extrafields+1, ncol( tempdata ) ) ]
        }

        printlog( "nrow =", nrow( tempdata ), "ncol =", ncol( tempdata ) )

        # Extract scenario and date
        if( SCENARIO_FIELD_NAME %in% names( tempdata ) ) {
            #           printlog( "Separating scenario and date" )
            splitinfo <- str_split_fixed( tempdata[ , SCENARIO_FIELD_NAME ], ",date=", 2 )
            tempdata$scenario <- splitinfo[ , 1 ]
            tempdata$date <- splitinfo[ , 2 ]
        }

        # Extract AEZ, if available - this is very specific and breakable
        searchstring <- "AEZ[0-9]{1}"
        splitstring <- "AEZ"
        if( !is.na( splitstring ) ) {
            #           printlog( "Looking for", splitstring )
            for( j in 1:ncol( tempdata ) ) {
                if( grepl( searchstring, tempdata[ 1, j ] ) ) {
                    printlog( splitstring, "data located in column", j )
                    dtemp <- as.data.frame( str_split_fixed( tempdata[ , j ], splitstring, 2 ) )
                    #                   print(head(dtemp))
                    tempdata[ , j ] <- dtemp[ , 1 ]
                    tempdata[ splitstring ] <- dtemp[,2] #as.factor( as.numeric( dtemp[ , 2 ] ) )
                }
            }
        }

        #       printlog( "Melting..." )
        yearfields <- grep( yearpat, names( tempdata ) )
        tempdata <- melt( tempdata, measure.vars=yearfields )

        # Make a better year field and assign file name field
        tempdata$Year <- as.numeric( substr( tempdata$variable, 2, length( tempdata$variable ) ) )
        tempdata$variable <- NULL
        tempdata[ , FILE_FIELD_NAME ] <- strsplit( basename( fn ), ".csv" )[[ 1 ]][ 1 ]

        if( !(table_name %in% names( tables ) )) {
            tables[[ table_name ]] <- tempdata
        } else {
            tables[[ table_name ]] <- rbind(tables[[ table_name ]], tempdata)
        }
    } # for i

    return( tables )
} # parse_mi_output

# -----------------------------------------------------------------------------
parse_mi_output_pic_progress <- function(fn) {

  tables <- list()
  use_tablenames <- TRUE
  headerline <- "scenario"
  yearpat <- "X[0-9]{4}"

  # Read file safely
  fdata <- tryCatch({
    scan(fn, what = character(), sep = "\n", blank.lines.skip = FALSE, quiet = TRUE)
  }, error = function(err) {
    stop("Error reading file: ", err)
  })

  error_lines <- grep("had error: java\\.lang\\.Exception: The query returned no results\\.",
                      scan(fn, what = character(), sep = "\n", quiet = TRUE))

  tableheaders <- grep(headerline, fdata)
  n_tables <- length(tableheaders)

  # Initialize progress bar
  pb <- txtProgressBar(min = 0, max = n_tables, style = 3)

  FILE_FIELD_NAME <- "file"  # Ensure it's defined as a string

  for (i in seq_len(n_tables)) {
    if (use_tablenames) {
      table_name <- fdata[tableheaders[i] - 1]
    } else {
      table_name <- i
    }

    nskip <- tableheaders[i] - 1
    headers <- fdata[tableheaders[i]]
    extrafields <- 0
    while (substr(headers, nchar(headers), nchar(headers)) == ",") {
      headers <- substr(headers, 1, nchar(headers) - 1)
      extrafields <- extrafields + 1
    }

    # Compute nrows and error lines correctly
    if (i == n_tables) {
      nrows <- length(fdata) - tableheaders[i]
      error_inside <- error_lines[error_lines >= tableheaders[i]]
    } else {
      nrows <- tableheaders[i + 1] - tableheaders[i] - 1 - use_tablenames
      error_inside <- error_lines[error_lines >= tableheaders[i] & error_lines <= tableheaders[i + 1]]
    }
    nrows_corrected <- nrows - length(error_inside)

    # Read table
    tempdata <- read.table(fn, row.names = NULL, skip = nskip, nrows = nrows_corrected,
                           header = TRUE, stringsAsFactors = FALSE, sep = ",",
                           comment.char = GCAM_DATA_COMMENT)

    # Remove extra columns if needed
    if (extrafields > 0 & extrafields < ncol(tempdata)) {
      tempdata <- tempdata[, 1:(ncol(tempdata) - extrafields)]
    }

    # Extract scenario and date
    if (SCENARIO_FIELD_NAME %in% names(tempdata)) {
      splitinfo <- str_split_fixed(tempdata[, SCENARIO_FIELD_NAME], ",date=", 2)
      tempdata$scenario <- splitinfo[, 1]
      tempdata$date <- splitinfo[, 2]
    }

    # Extract AEZ
    searchstring <- "AEZ[0-9]{1}"
    splitstring <- "AEZ"
    if (!is.na(splitstring)) {
      for (j in seq_len(ncol(tempdata))) {
        if (grepl(searchstring, tempdata[1, j])) {
          dtemp <- as.data.frame(str_split_fixed(tempdata[, j], splitstring, 2))
          tempdata[, j] <- dtemp[, 1]
          tempdata[, splitstring] <- dtemp[, 2]
        }
      }
    }

    #       printlog( "Melting..." )
    yearfields <- grep( yearpat, names( tempdata ) )
    tempdata <- melt( tempdata, measure.vars=yearfields )

    # Make a better year field and assign file name field
    tempdata$Year <- as.numeric( substr( tempdata$variable, 2, length( tempdata$variable ) ) )
    tempdata$variable <- NULL
    tempdata[ , FILE_FIELD_NAME ] <- strsplit( basename( fn ), ".csv" )[[ 1 ]][ 1 ]

    # Store in list
    if (!(table_name %in% names(tables))) {
      tables[[table_name]] <- tempdata
    } else {
      tables[[table_name]] <- rbind(tables[[table_name]], tempdata)
    }

    # Update progress bar
    setTxtProgressBar(pb, i)
  }

  close(pb)
  return(tables)
}

# -----------------------------------------------------------------------------
# Get a table of GCAM output by title (or table number).
extract_data <- function( t, fnum=-1 ) {
    if(fnum != -1) {
        d <- tables[[ FILES[ fnum ] ]][[ t ]]
    } else {
        d <- tables[[ FILES[ 1 ] ]][[ t ]]
        i <- 2
        while(i <= length(FILES)) {
            d <- rbind(d, tables[[ FILES[ i ] ]][[ t ]])
            i <- i + 1
        }
    }
    return(d)
}	# convenience function
# -----------------------------------------------------------------------------
# Get a table of GCAM output by title from a single tables list.
extract_data_one <- function(t, tables) {
    # Return the table by name from the parsed tables list
    d <- tables[[ t ]]
    return(d)
}   # convenience function

parse_output_AR6_data <- function(df) {
  df <- df %>%
    mutate(
      scenario_SSP = stringr::str_extract(Scenario, "SSP[1-5]"),
      scenario_SSP = ifelse(is.na(scenario_SSP), "N/S", scenario_SSP),
      degree_215 = stringr::str_extract(Scenario, "1.5C|2C"),
      degree_215 = ifelse(is.na(degree_215), "N/S", degree_215)
    )
  
  df_long <- df %>%
    mutate(Model_Scenario = paste(Model, Scenario, sep = "_")) %>%
    select(-Scenario, -Region, -Variable, -Model) %>%  # keep scenario_SSP!
    tidyr::pivot_longer(
      cols = starts_with("X"), names_to = "year",
      values_to = "value", names_prefix = "X"
    ) %>%
    filter(!is.na(value)) %>%
    mutate(year = as.numeric(year))
  
  return(df_long)
}

parse_output_AR6_data_region <- function(df) {
  df <- df %>%
    mutate(
      scenario_SSP = stringr::str_extract(Scenario, "SSP[1-5]"),
      scenario_SSP = ifelse(is.na(scenario_SSP), "N/S", scenario_SSP),
      degree_215 = stringr::str_extract(Scenario, "1.5C|2C"),
      degree_215 = ifelse(is.na(degree_215), "N/S", degree_215)
    )
  
  df_long <- df %>%
    mutate(Model_Scenario = paste(Model, Scenario, sep = "_")) %>%
    select(-Scenario, -Variable, -Model) %>%  # keep scenario_SSP!
    rename(region = Region) %>%
    tidyr::pivot_longer(
      cols = starts_with("X"), names_to = "year",
      values_to = "value", names_prefix = "X"
    ) %>%
    filter(!is.na(value)) %>%
    mutate(year = as.numeric(year))
  
  return(df_long)
}
